name: chart-powerdns pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'HMCTS Github'
variables:
  helmWait: 300
  helmVersion: 1.13.0
  serviceConnection: "azurerm-sandbox"
  aksResourceGroup: "cnp-aks-sandbox-rg"
  aksCluster: "cnp-aks-sandbox-cluster"
  acrName: "hmcts"

jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: powerdns
      chartReleaseName: chart-powerdns-ci-test
      chartNamespace: chart-tests
      helmVersion: $(helmVersion)
      serviceConnection: $(serviceConnection)
      aksResourceGroup: $(aksResourceGroup)
      aksCluster: $(aksCluster)
      acrName: $(acrName)
      helmInstallTimeout: $(helmWait)
- job: ValidateExternalDB
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: powerdns
      chartReleaseName: chart-powerdns-ci-test-externaldb
      chartNamespace: chart-tests
      helmVersion: $(helmVersion)
      serviceConnection: $(serviceConnection)
      aksResourceGroup: $(aksResourceGroup)
      aksCluster: $(aksCluster)
      acrName: $(acrName)
      helmInstallTimeout: $(helmWait)
      valuesFile: ci-values-externaldb.yaml
- job: ValidateAll
  displayName: Validate with loadbalancer, ingress and external database
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: powerdns
      chartReleaseName: chart-powerdns-ci-test-all
      chartNamespace: chart-tests
      helmVersion: $(helmVersion)
      serviceConnection: $(serviceConnection)
      aksResourceGroup: $(aksResourceGroup)
      aksCluster: $(aksCluster)
      acrName: $(acrName)
      helmInstallTimeout: $(helmWait)
      valuesFile: ci-values-all.yaml

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn:
  - Validate
  - ValidateExternalDB
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: powerdns
      chartReleaseName: chart-powerdns
      chartNamespace: chart-tests
      helmInstallTimeout: $(helmWait)
