name: chart-powerdns pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'HMCTS Github'
variables:
  helmWait: 600

jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: powerdns
      chartReleaseName: chart-powerdns-ci-test
      chartNamespace: chart-tests
      helmInstallTimeout: $(helmWait)
- job: ValidateExternalDB
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: powerdns
      chartReleaseName: chart-powerdns-ci-test-externaldb
      chartNamespace: chart-tests
      helmInstallTimeout: $(helmWait)
      valuesFile: ci-values-externaldb.yaml

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn:
  - Validate
  - ValidateExternalDB
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: powerdns
      chartReleaseName: chart-powerdns
      chartNamespace: chart-tests
      helmInstallTimeout: $(helmWait)
