# Default values for pdns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
api:
  enabled: yes
  key: PowerDNSAPI

webserver:
  allowFrom: 0.0.0.0/0
dnsupdate:
  enabled: no

image:
  repository: hmcts/powerdns-auth
  tag: 4.1.5r2-v0.0.1
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP

resources:
  limits:
   cpu: 500m
   memory: 1024Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

environment:
  AUTOCONF: postgres
  PGSQL_DB: postgres
  PGSQL_HOST: pdns-chart-test.postgres.database.azure.com
  PDNS_DEFAULT_SOA_NAME: root.platform.hmcts.net
  PDNS_API: 'yes'
  PDNS_API_KEY: changeme
  PDNS_WEBSERVER: 'yes'
  PDNS_WEBSERVER_ADDRESS: '0.0.0.0'
  PDNS_WEBSERVER_ALLOW_FROM: '0.0.0.0/0'

keyVault:
  vaultName: infra-vault-nonprod
  resourceGroup: cnp-core-infra
  subscriptionId: 1c4f0704-a29e-403d-b719-b90c34ef14c9
  tenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
  secrets:
    dbUsernameSecret: chart-pdns-db-username
    dbPasswordSecret: chart-pdns-db-password

ui:
  enabled: true
  replicaCount: 1
  image:
    repository: hmcts/powerdns-admin:latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  environment:
    PDA_DB_NAME: 'postgres'
    PDA_DB_HOST: 'pdns-chart-test.postgres.database.azure.com'
    PDA_DB_PORT: '5432'
    SAML_ENABLED: 'true'
    SAML_METADATA_URL: 'https://login.microsoftonline.com/rpe899.onmicrosoft.com/FederationMetadata/2007-06/FederationMetadata.xml'
    SAML_GROUP_ADMIN_NAME: '356b57d8-84f4-457a-b49e-9500820c0b2d'
    SAML_GROUP_TO_ACCOUNT_MAPPING: '9189d86a-e260-4c3d-8227-803123cdce84=cnp'
    SAML_SP_ENTITY_ID: 'https://rpe899.onmicrosoft.com/384ce2b5-fbd1-43db-9621-80394401edfb'
    PDA_SITE_NAME: 'HMCTS'
    PDNS_API_KEY: changeme
    PDNS_HOST: 'chart-powerdns-ci-test-externaldb-dns-api'
    PDNS_PORT: '80'

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
    hostname: dns.platform.hmcts.net
    tls: false

postgresql:
  enabled: false
