---

version: '2.1'

services:
  postgres:
    image: postgres:9.6-alpine
    command: postgres -c 'max_connections=250'
    volumes:
      - ./docker/database/init-db-v9.6.sh:/docker-entrypoint-initdb.d/init-db.sh
      - shared-database-data:/var/lib/postgresql/data
    healthcheck:
      test: psql -c 'select 1' -d postgres -U postgres
      retries: 40
    mem_limit: 320m
    memswap_limit: 0
    ports:
      - 5420:5432
  pdns:
    image: psitrax/powerdns
    environment: 
      AUTOCONF: postgres
      PGSQL_USER: pdns
      PGSQL_PASS: pdns
      PGSQL_HOST: postgres
      PDNS_DEFAULT_SOA_NAME: root.platform.hmcts.net
      PDNS_API: 'yes'
      PDNS_API_KEY: changeme
      PDNS_WEBSERVER: 'yes'
      PDNS_WEBSERVER_ADDRESS: '0.0.0.0'
      PDNS_WEBSERVER_ALLOW_FROM: '0.0.0.0/0'
    ports:
      - 8081:8081

volumes:
  shared-database-data:  