apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}
    helm.sh/chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if  .Values.service.LoadBalancerIP }}
  loadBalancerIP: {{ .Values.service.LoadBalancerIP }}
  {{- end }}
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}
    release: {{ .Release.Name }}

