apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}-dns-api
  labels:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}-dns-api
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}-dns-api
    app.kubernetes.io/instance: {{ template "pdns.fullname" . }}-dns-api
spec:
  ports:
    - name: dns-api
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}
