---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pdns.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}-ui
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "pdns.fullname" . }}-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "pdns.fullname" . }}-ui
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.db.external }}
      volumes:
        - name: ui-secrets
          flexVolume:
            driver: "azure/kv"
            secretRef:
              name: kvcreds
            options:
              usepodidentity: "false"
              keyvaultname: {{ .Values.keyVault.vaultName}}
              keyvaultobjectnames: {{ .Values.keyVault.usernameSecret }};{{ .Values.keyVault.dbPasswordSecret }}
              keyvaultobjecttypes: secret
              resourcegroup: {{ .Values.keyVault.resourceGroup }}
              subscriptionid: {{ .Values.keyVault.subscriptionId }}
              tenantid: {{ .Values.keyVault.tenantId }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-ui
          image: {{ .Values.ui.image.repository }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        {{- if .Values.db.external }}
          volumeMounts:
          - name: ui-secrets
            mountPath: /secrets
            readOnly: true
          command: |
            ["/bin/sh", "-c", "export PDA_DB_USER=$(cat /secrets/{{ .Values.keyVault.secrets.dbUsernameSecret }}); \
                               export PDA_DB_PASSWORD=$(cat /secrets/{{ .Values.keyVault.secrets.dbUsernamePassword }}); \
                               /entrypoint.sh"]
        {{- end }}
          env:
{{- (include "pdns.environment" .Values.ui.environment) | indent 10 }}
          - name: PDNS_API_KEY
            value: {{ .Values.api.key }}
          - name: PDNS_HOST
            value: {{ .Release.Name }}-pdns-dns-api
          - name: PDNS_PORT
            value: '80'
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
    {{- with .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
