{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pdns.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.uiHostName }}
        - {{ .Values.ingress.apiHostName }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.apiHostName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-api
              servicePort: api
    - host: {{ .Values.ingress.uiHostName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-ui
              servicePort: ui
{{- end }}
