apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}
    helm.sh/chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "pdns.name" . }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns-tcp
  selector:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}-dns-api
  labels:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}-dns-api
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}-dns-api
    app.kubernetes.io/instance: {{ template "pdns.fullname" . }}-dns-api
spec:
  ports:
    - name: dns-api
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}