---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pdns.fullname" . }}-ui
  labels:
    app: {{ template "pdns.name" . }}-ui
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pdns.name" . }}-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pdns.name" . }}-ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-ui
          image: {{ .Values.ui.image.repository }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
{{- (include "pdns.environment" .Values.ui.environment) | indent 10 }}
          - name: PDNS_API_KEY
            value: {{ .Values.pdns.api.key }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
    {{- with .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
