---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}-ui
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}-ui
    app.kubernetes.io/instance: {{ template "pdns.fullname" . }}-ui
spec:
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ template "pdns.fullname" . }}-ui