# Default values for pdns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: hmcts/powerdns-auth:4.1.5r2-v0.0.1
  tag: 4.1.5r2
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  loadBalancerIP: {}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # hopefully will work in next version of 1.12.x https://github.com/kubernetes/kubernetes/pull/74494
    # service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"

resources:
  limits:
   cpu: 500m
   memory: 1024Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

environment:
  AUTOCONF: postgres
  PGSQL_USER: pdns
  PGSQL_PASS: pdns
  PGSQL_DB: postgres
  PGSQL_HOST: powerdns-postgresql
  PDNS_DEFAULT_SOA_NAME: root.platform.hmcts.net
  PDNS_API: 'yes'
  PDNS_WEBSERVER: 'yes'
  PDNS_WEBSERVER_PORT: '8081'
  PDNS_WEBSERVER_ADDRESS: '0.0.0.0'
  PDNS_WEBSERVER_ALLOW_FROM: '0.0.0.0/0'
  PDNS_UPDATE: 'no'

keyVault:
  vaultName: {}
  resourceGroup: {}
  subscriptionId: {}
  tenantId: {}
  secrets:
    dbUsernameSecret: {}
    dbPasswordSecret: {}
    pdnsApiKeySecret: {}

ui:
  enabled: true
  replicaCount: 1
  image:
    repository: hmcts/powerdns-admin:latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  environment:
    PDA_DB_USER: 'pdns'
    PDA_DB_PASSWORD: 'pdns'
    PDA_DB_NAME: 'pdns_ui'
    PDA_DB_HOST: 'powerdns-postgresql'
    PDA_DB_PORT: '5432'
    SAML_ENABLED: 'true'
    SAML_METADATA_URL: 'https://login.microsoftonline.com/rpe899.onmicrosoft.com/FederationMetadata/2007-06/FederationMetadata.xml'
    SAML_GROUP_ADMIN_NAME: '356b57d8-84f4-457a-b49e-9500820c0b2d'
    SAML_GROUP_TO_ACCOUNT_MAPPING: '9189d86a-e260-4c3d-8227-803123cdce84=cnp'
    SAML_SP_ENTITY_ID: 'https://rpe899.onmicrosoft.com/384ce2b5-fbd1-43db-9621-80394401edfb'
    PDA_SITE_NAME: 'HMCTS'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hostname: dns.platform.hmcts.net
    tls: false

postgresql:
  postgresqlUsername: pdns
  postgresqlPassword: pdns
  postgresqlDatabase: pdns
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "pdns_ui" WITH OWNER = pdns ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  persistence:
    enabled: false
